apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer  # You can use NodePort or ClusterIP instead if you are running Kubernetes locally or have an external load balancer
